### 1 create config
PUT http://{{host}}/metadata/sources/video/confKeys/panda
Content-Type: application/json

{"url":"https://gcwbcdks.v.kcdnvip.com/gcwbcd/cdrmipanda_1/index.m3u8","interval":10000}

### 1 create stream
POST http://{{host}}/streams
Content-Type: application/json

{
  "sql": "create stream TfliteVideo () WITH (FORMAT=\"binary\", TYPE=\"video\", CONF_KEY=\"panda\")"
}


### 2 install tfLite plugin and image plugin
### 3 upload image model



### 4 create rule
POST http://{{host}}/rules
Content-Type: application/json

{
  "id": "ruleTfLiteVideo",
  "sql": "SELECT tfLite(\"mobilenet_quant_v1_224\", resize(self, 224, 224, true)) FROM TfliteVideo",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://emqx:1883",
        "topic": "demo1TfliteVideo_result",
        "sendSingle": true
      }
    }
  ]
}

### 4 update rule
PUT http://{{host}}/rules/ruleDecode
Content-Type: application/json

{
  "id": "ruleTfLiteVideo",
  "sql": "SELECT tfLite(\"mobilenet_quant_v1_224\", resize(self, 224, 224, true)) FROM TfliteVideo",
  "actions": [
    {
      "mqtt": {
        "server": "tcp://emqx:1883",
        "topic": "demo1TfliteVideo_result",
        "sendSingle": true
      }
    }
  ]
}